# Full struct in cmd/prowgen/prowgen.go#Config

config:
  branches:
    "release-v1.4":
      openShiftVersions:
        - 4.11
        - 4.6
    "release-v1.5":
      openShiftVersions:
        - 4.11
        - 4.8
    "release-v1.6":
      openShiftVersions:
        - 4.11
        - 4.8
    "release-v1.7":
      openShiftVersions:
        - 4.11
        - 4.8
    "release-v1.8":
      openShiftVersions:
        - 4.11
        - 4.8
    "release-next":
      openShiftVersions:
        - 4.11
        - 4.8

repositories:
  - org: openshift-knative
    repo: eventing
    imagePrefix: knative-eventing
    slackChannel: "#knative-eventing-ci"
    e2e:
      matches:
        - ".*e2e$"
        - ".*reconciler.*"
        - ".*conformance.*"
