name: Multiarch KO builds

on:
  workflow_call:
    inputs:
      # Deprecated, left for backward compatibility but it is unused
      goversion:
        description: A version of Go
        default: 1.21.x
        required: false
        type: string
      koversion:
        description: A KO version
        default: v0.12.0
        required: false
        type: string
      platforms:
        default: all
        description: A list of platforms to build the images for
        required: false
        type: string
      registry:
        default: quay.io
        description: A registry to push image to
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  multiarch-build:
    name: Build images
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup ko
        uses: imjasonh/setup-ko@v0.9
        with:
          version: ${{ inputs.koversion }}

      - name: Setup make
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Login to quay.io
        env:
          quay_user: ${{ secrets.QUAY_USER }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}
        run: |
          ko login -u="${quay_user}" -p="${quay_password}" quay.io

      - name: Build and push multiarch test images
        env:
          ref: ${{ github.ref_name }}
        run: |
          echo "Building images from ${GITHUB_REF}@${GITHUB_SHA}"
          # Ref: https://regex101.com/r/gcxd4h/1
          major_minor="$(echo "$ref" | sed -E 's/^.*?v?([[:digit:]]+)\.([[:digit:]]+).*/\1.\2/')"
          make test-images DOCKER_REPO_OVERRIDE=${{ inputs.registry }}/${{ github.repository }}/ \
            KO_FLAGS="--platform=${{ inputs.platforms }} --sbom=none" TEST_IMAGE_TAG=v${major_minor}
